### ISSUE TITLE
NpoiExtension.cs 从“DateTime”到“Double”的强制转换无效。

### ISSUE THREAD

**Issue by VAllens** [xyting/NPOI.Extension#10]
在property.PropertyType == typeof(DateTime)这个else if判断分支，要加上或者等于DateTime?，并且修改Convert.ToDateTime为其它方法才行。
else if (property.PropertyType == typeof(DateTime) **|| property.PropertyType == typeof(DateTime?)**)
                        {
                            if (dateCellStyle == null)
                            {
                                // create the cache.
                                dateCellStyle = workbook.CreateCellStyle();

                                var dateFormat = workbook.CreateDataFormat();

                                dateCellStyle.DataFormat = dateFormat.GetFormat(Excel.Setting.DateFormatter);
                            }

                            cell.CellStyle = dateCellStyle;

                            **DateTime? time = value.ChangeType((DateTime?)null);
                            if (time.HasValue)
                            {
                                cell.SetCellValue(time.Value);
                            }
                            else
                            {
                                cell.SetCellValue("");
                            }**
                        }

**Comment by rigofunc** [comment]
@VAllens Thanks, you can give this repo a PR.

**Comment by rigofunc** [comment]
I will fix this today and release a new version.

**Comment by rigofunc** [comment]
Done, [NPOI.Extension v1.4.2](https://www.nuget.org/packages/NPOI.Extension/1.4.2)

**Comment by VAllens** [comment]
Good. ^_^.
Thanks.

**Comment by rigofunc** [comment]
@VAllens Thanks your demo code, but, my implementation maybe better, please review.
