### ISSUE TITLE
errors when load from excel files

### ISSUE THREAD

**Issue by mrtylerzhou** [xyting/NPOI.Extension#11]
1.export to excel just fine,but when loading excel file,I came across a lot of formatter problems.(even use the excel file generate by this extension).
2.suggestions:Will you plan to support multiple Statistics instance,I need sum,avg when exporting excel.
3.suggestions:will you plan to support custom format cell other than just customize datetime

**Comment by rigofunc** [comment]
@mrtylerzhou Please provide more info about the bug(s). And thanks your suggenstions, I'll first to support Fluent configuration API in v2.0, and than, I will support mare formatter and more configuration api, PR wellcome.

**Comment by rigofunc** [comment]
@mrtylerzhou I had implemented the `fluent` configuration api, and your `2. suggestions`. had been supported. The [v2.0.0](https://www.nuget.org/packages/NPOI.Extension/2.0.0) had released

**Comment by rigofunc** [comment]
In v2.1, I will add more formmater setting.

**Comment by rigofunc** [comment]
@mrtylerzhou The `Excel.Load<T>(..., valueConverter = null)` have an optional converter, so you can pass your converter to handle cell value.

**Comment by rigofunc** [comment]
[v2.1](https://www.nuget.org/packages/NPOI.Extension/2.1.0) had been released.
