### ISSUE TITLE
is there any plan to support datatable/dataset

### ISSUE THREAD

**Issue by mrtylerzhou** [xyting/NPOI.Extension#18]
this extension really a great time saver.But In my practice,most of times i just simply to convert database data to excel files.it is tedious to map db structures to class files.so i think it will be better to just simply transform a datatable/dataset to excel file(s).But it seems that currently this extension does not support datatable. 

so,I looking forward that datatable to excel will be supported in the next version for barely transfer db to excel without and modifications.

**Comment by rigofunc** [comment]
Good suggestions! But I do not like `datatable` and `dataset` API, so, to impls your suggestions, I will support directly export database to excel file in the next release.

**Comment by rigofunc** [comment]
But, the future features will be supported by [FluentExcel](https://github.com/Arch/FluentExcel), and will only support `Fluent API`. so, all the issues from this repo will solved or fixed by `FluentExcel` repo.

**Comment by rigofunc** [comment]
This plan had been delay to `FluentExcel` v2 or v2.x
