### ISSUE TITLE
提个小问题

### ISSUE THREAD

**Issue by JHeLiu** [xyting/NPOI.Extension#21]
1.如果可以，能否把代码注释一起打包?
2.对于输出到 工作簿表格文件，有考虑过要设计一个开关 是否覆盖与重新创建的操作吗?

**Comment by rigofunc** [comment]
使用[FluentExcel](https://github.com/Arch/FluentExcel)，FluentExcel是我长期维护的一个组件，你说的这个开关在FluentExcel已经有了。注释打包，我下次打包新的FluentExcel的时候注意一下。

**Comment by JHeLiu** [comment]
我在 nuget 上 NPOI.Extension 获取你的项目，你现在是已经更名为 FluentExcel 对吗？

**Comment by rigofunc** [comment]
FluentExcel是NPOI.Extension的进化版本，nuget包也有的。

**Comment by JHeLiu** [comment]
是的，我已经看到了，很好的库，我看到了你的旧版本  NPOI.Extension 它是一个自定义的 特性来扩展一些属性， 在 FluentExcel 看到你使用了MS自带的特性，如果我需要做一个样式 或者特性的转换，我应该使用 另一种方式 去实现吗？
